export const ADD_FORM_REQUEST = "ADD_FORM_REQUEST";
export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCES";
export const ADD_FORM_FAIL = "ADD_FORM_FAIL";
export const ADD_FORM_RESET = "ADD_FORM_RESET";

export const GET_ALL_FORM_REQUEST = "GET_ALL_FORM_REQUEST";
export const GET_ALL_FORM_SUCCESS = "GET_ALL_FORM_SUCCES";
export const GET_ALL_FORM_FAIL = "GET_ALL_FORM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";